[package]
name = "rocket_contrib"
version = "0.0.10"
authors = ["Sergio Benitez <sb@sergio.bz>"]

[features]
default = ["json"]
json = ["serde", "serde_json"]
tera_templates = ["tera", "templates"]
handlebars_templates = ["handlebars", "templates"]

# Internal use only.
templates = ["serde", "serde_json", "lazy_static_macro", "glob"]
lazy_static_macro = ["lazy_static"]

[dependencies]
rocket = { path = "../lib/" }
log = "^0.3"

# JSON and templating dependencies.
serde = { version = "^0.8", optional = true }
serde_json = { version = "^0.8", optional = true }

# Templating dependencies only.
handlebars = { version = "^0.21", optional = true, features = ["serde_type"] }
glob = { version = "^0.2", optional = true }
lazy_static = { version = "^0.2", optional = true }
tera = { version = "^0.3", optional = true }
