environment:
  matrix:
    - TARGET: i686-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly

# Show RDP information on init.
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Install Rust and Cargo
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

# Disable Appveyor's build stage. This prevents the "directory does not contain
# a project or solution file" error
build: false

# Equivalent to Travis' `script` phase
test_script:
  - sh "./scripts/test.sh"

branches:
  only:
    - master
    # IMPORTANT Regex to match tags. Required, or appveyor may not trigger
    # deploys when a new tag is pushed. This regex matches semantic versions
    # like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/
