[workspace]
members = [
  "lib/",
  "codegen/",
  "contrib/",
  "examples/cookies",
  "examples/errors",
  "examples/extended_validation",
  "examples/forms",
  "examples/hello_person",
  "examples/query_params",
  "examples/hello_world",
  "examples/manual_routes",
  "examples/optional_redirect",
  "examples/optional_result",
  "examples/redirect",
  "examples/static_files",
  "examples/todo",
  "examples/content_types",
  "examples/hello_ranks",
  "examples/testing",
  "examples/from_request",
  "examples/stream",
  "examples/json",
  "examples/handlebars_templates",
  "examples/form_kitchen_sink",
  "examples/config",
  "examples/hello_alt_methods",
  "examples/raw_upload",
  "examples/pastebin",
]
