max_width = 90
fn_call_width = 90
condense_wildcard_suffixes = true
error_on_line_overflow = false
fn_args_density = "CompressedIfEmpty"
fn_call_style = "Visual"
chain_one_line_max = 80
imports_layout = "Horizontal"
match_pattern_separator_break_point = "Front"
struct_lit_width = 40
use_try_shorthand = true
where_style = "Legacy"
where_density = "Vertical"
where_layout = "HorizontalVertical"
