[package]
name = "rocket_codegen"
version = "0.4.0-dev"
authors = ["Sergio Benitez <sb@sergio.bz>"]
description = "Procedural macros for the Rocket web framework."
documentation = "https://api.rocket.rs/v0.4/rocket_codegen/"
homepage = "https://rocket.rs"
repository = "https://github.com/SergioBenitez/Rocket"
readme = "../../README.md"
keywords = ["rocket", "web", "framework", "code", "generation"]
license = "MIT/Apache-2.0"
build = "../lib/build.rs"

# if publishing, add to config scripts
publish = false

[lib]
proc-macro = true

[dependencies]
indexmap = "1.0"
quote = "0.6.1"
rocket_http = { version = "0.4.0-dev", path = "../http/" }

[build-dependencies]
yansi = "0.4"
version_check = "0.1.3"

[dependencies.derive_utils]
git = "https://github.com/SergioBenitez/derive-utils"
rev = "62f361f"

[dev-dependencies]
rocket = { version = "0.4.0-dev", path = "../lib" }
compiletest_rs = "0.3.14"
