[package]
name = "managed_queue"
version = "0.0.0"
workspace = "../.."

[dependencies]
crossbeam = "*"
rocket = { path = "../../lib" }
rocket_codegen = { path = "../../codegen" }

[dev-dependencies]
rocket = { path = "../../lib", features = ["testing"] }
