# Except for the session key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.

[development]
address = "localhost"
port = 8000
log = "normal"
hi = "Hello!"
is_extra = true

[staging]
address = "0.0.0.0"
port = 80
log = "normal"
# don't use this key! generate your own and keep it private!
session_key = "VheMwXIBygSmOlZAhuWl2B+zgvTN3WW5"

[production]
address = "0.0.0.0"
port = 80
log = "critical"
# don't use this key! generate your own and keep it private!
session_key = "adL5fFIPmZBrlyHk2YT4NLV3YCk2gFXz"
