[package]
name = "rocket_codegen"
version = "0.0.9"
authors = ["Sergio Benitez <sb@sergio.bz>"]

[lib]
plugin = true

[dependencies]
rocket = { path = "../lib/" }
log = "^0.3"

[dev-dependencies]
compiletest_rs = "^0.2"
