[package]
name = "rocket_http"
version = "0.4.0-dev"
authors = ["Sergio Benitez <sb@sergio.bz>"]
description = """
Types, traits, and parsers for HTTP requests, responses, and headers.
"""
documentation = "https://api.rocket.rs/rocket_http/"
homepage = "https://rocket.rs"
repository = "https://github.com/SergioBenitez/Rocket"
readme = "../../README.md"
keywords = ["rocket", "web", "framework", "http"]
license = "MIT/Apache-2.0"
categories = ["web-programming"]

[features]
tls = ["rustls", "hyper-sync-rustls"]

[dependencies]
smallvec = "0.6"
percent-encoding = "1"
hyper = { version = "0.10.13", default-features = false }
time = "0.1"
indexmap = "1.0"
rustls = { version = "0.13", optional = true }
state = "0.4"
cookie = { version = "0.11", features = ["percent-encode", "secure"] }
pear = { git = "http://github.com/SergioBenitez/Pear", rev = "d221e16dd" }
unicode-xid = "0.1"

[dependencies.hyper-sync-rustls]
version = "=0.3.0-rc.3"
features = ["server"]
optional = true

[dev-dependencies]
rocket = { version = "0.4.0-dev", path = "../lib" }
