[package]
name = "todo"
version = "0.0.1"
authors = ["Sergio Benitez <sb@sergio.bz>"]

[dependencies]
rocket = { path = "../../lib" }
rocket_macros = { path = "../../macros" }
lazy_static = "*"
tera = { git = "https://github.com/Keats/tera" }
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"
diesel = { git = "https://github.com/diesel-rs/diesel.git", features = ["sqlite"] }
diesel_codegen = { git = "https://github.com/diesel-rs/diesel.git", default_features = false, features = ["sqlite"] }
