[package]
name = "todo"
version = "0.0.1"
authors = ["Sergio Benitez <sb@sergio.bz>"]
workspace = "../../"

[dependencies]
rocket = { path = "../../lib" }
rocket_codegen = { path = "../../codegen" }
lazy_static = "*"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
diesel = "0.8"
diesel_codegen = { version = "0.8", features = ["sqlite"] }

[dependencies.rocket_contrib]
path = "../../contrib"
default_features = false
features = [ "tera_templates" ]
