[package]
name = "todo"
version = "0.0.1"
workspace = "../../"

[dependencies]
rocket = { path = "../../lib" }
rocket_codegen = { path = "../../codegen" }
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
diesel = { version = "0.10", features = ["sqlite"] }
diesel_codegen = { version = "0.10", features = ["sqlite"] }

[dependencies.rocket_contrib]
path = "../../contrib"
default_features = false
features = [ "tera_templates" ]
