[package]
name = "hello_ranks"
version = "0.0.1"
authors = ["Sergio Benitez <sb@sergio.bz>"]
workspace = "../../"

[dependencies]
rocket = { path = "../../lib" }
rocket_macros = { path = "../../macros" }
